# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChatForm(object):
    def setupUi(self, ChatForm):
        ChatForm.setObjectName("ChatForm")
        ChatForm.resize(1386, 744)
        ChatForm.setStyleSheet("#ChatForm{background-image: url(:/images/images/baground.jpg);}")
        self.textBrowser = QtWidgets.QTextBrowser(ChatForm)
        self.textBrowser.setGeometry(QtCore.QRect(10, 124, 1165, 391))
        self.textBrowser.setStyleSheet("QTextBrowser#textBrowser{\n"
                                       "    border: none;\n"
                                       "    font-size: 20px;\n"
                                       "    color: #58C9FF;\n"
                                       "}")
        self.textBrowser.setObjectName("textBrowser")
        self.textEdit = QtWidgets.QTextEdit(ChatForm)
        self.textEdit.setGeometry(QtCore.QRect(10, 569, 1160, 111))
        self.textEdit.setStyleSheet("QTextEdit#textEdit{\n"
                                    "    border: none;\n"
                                    "    font-size: 20px;\n"
                                    "}")
        self.textEdit.setObjectName("textEdit")
        self.sendButton = QtWidgets.QPushButton(ChatForm)
        self.sendButton.setGeometry(QtCore.QRect(1024, 687, 131, 41))
        self.sendButton.setStyleSheet("background-image: url(:/images/images/sendbtn.png) transparent no-repeat;\n"
                                      "border-radius:2px;")
        self.sendButton.setText("")
        self.sendButton.setObjectName("sendButton")
        self.pushButton = QtWidgets.QPushButton(ChatForm)
        self.pushButton.setGeometry(QtCore.QRect(896, 688, 106, 40))
        self.pushButton.setStyleSheet("background-image: url(:/images/images/closebtn.png)transparent no-repeat;\n"
                                      "border-radius:2px;")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.onlineStatus = QtWidgets.QLabel(ChatForm)
        self.onlineStatus.setGeometry(QtCore.QRect(789, 18, 71, 28))
        self.onlineStatus.setStyleSheet("font: 9pt \"仿宋\";\n"
                                        "color: #ffffff;\n"
                                        "font-weight: bold;")
        self.onlineStatus.setText("")
        self.onlineStatus.setObjectName("onlineStatus")
        self.chatName = QtWidgets.QLabel(ChatForm)
        self.chatName.setGeometry(QtCore.QRect(570, 18, 221, 28))
        self.chatName.setStyleSheet("\n"
                                    "font: 9pt \"黑体\";\n"
                                    "    font-size: 30px;\n"
                                    "    font-weight: bold;\n"
                                    "    color: #ffffff;")
        self.chatName.setText("")
        self.chatName.setObjectName("chatName")
        self.f_avatar = QtWidgets.QLabel(ChatForm)
        self.f_avatar.setGeometry(QtCore.QRect(1200, 60, 171, 171))
        self.f_avatar.setStyleSheet("border-radius:80px;")
        self.f_avatar.setText("")
        self.f_avatar.setObjectName("f_avatar")
        self.f_nickName = QtWidgets.QLabel(ChatForm)
        self.f_nickName.setGeometry(QtCore.QRect(1210, 240, 171, 41))
        self.f_nickName.setStyleSheet("font: 9pt \"黑体\";\n"
                                      "    font-size: 18px;\n"
                                      "    font-weight: bold;\n"
                                      "    color: #AAE0DB;")
        self.f_nickName.setText("")
        self.f_nickName.setObjectName("f_nickName")
        self.my_avatar = QtWidgets.QLabel(ChatForm)
        self.my_avatar.setGeometry(QtCore.QRect(1200, 570, 160, 160))
        self.my_avatar.setStyleSheet(" border-radius: 85px;")
        self.my_avatar.setText("")
        self.my_avatar.setObjectName("my_avatar")
        self.verticalLayoutWidget = QtWidgets.QWidget(ChatForm)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1220, 299, 161, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rootname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.rootname.setStyleSheet("\n"
                                    "    font-size: 16px;\n"
                                    "    font-weight: bold;\n"
                                    "    color: #D7DCE2;")
        self.rootname.setText("")
        self.rootname.setObjectName("rootname")
        self.verticalLayout.addWidget(self.rootname)
        self.gender = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.gender.setStyleSheet("    font-size: 16px;\n"
                                  "    font-weight: bold;\n"
                                  "    color: #D7DCE2;")
        self.gender.setText("")
        self.gender.setObjectName("gender")
        self.verticalLayout.addWidget(self.gender)
        self.email = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.email.setStyleSheet("    font-size: 16px;\n"
                                 "    font-weight: bold;\n"
                                 "    color: #D7DCE2;")
        self.email.setText("")
        self.email.setObjectName("email")
        self.verticalLayout.addWidget(self.email)
        self.address = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.address.setStyleSheet("    font-size: 16px;\n"
                                   "    font-weight: bold;\n"
                                   "    color: #D7DCE2;")
        self.address.setText("")
        self.address.setObjectName("address")
        self.verticalLayout.addWidget(self.address)
        self.email.raise_()
        self.rootname.raise_()
        self.gender.raise_()
        self.address.raise_()
        self.mes = QtWidgets.QLabel(ChatForm)
        self.mes.setGeometry(QtCore.QRect(10, 60, 941, 61))
        self.mes.setStyleSheet("   font: 9pt \"黑体\";\n"
                               "    border: none;\n"
                               "    font-size: 20px;\n"
                               "    color: #58C9FF;")
        self.mes.setText("")
        self.mes.setObjectName("mes")
        self.frame = QtWidgets.QFrame(ChatForm)
        self.frame.setGeometry(QtCore.QRect(1178, 355, 31, 31))
        self.frame.setStyleSheet("background-image: url(:/images/images/sex.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(ChatForm)
        self.frame_2.setGeometry(QtCore.QRect(1178, 404, 30, 30))
        self.frame_2.setStyleSheet("background-image: url(:/images/images/youxiang.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(ChatForm)
        self.frame_3.setGeometry(QtCore.QRect(1178, 305, 31, 31))
        self.frame_3.setStyleSheet("background-image: url(:/images/images/id.png);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(ChatForm)
        self.frame_4.setGeometry(QtCore.QRect(1178, 452, 30, 30))
        self.frame_4.setStyleSheet("background-image: url(:/images/images/address.png);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")

        self.retranslateUi(ChatForm)
        QtCore.QMetaObject.connectSlotsByName(ChatForm)

    def retranslateUi(self, ChatForm):
        _translate = QtCore.QCoreApplication.translate
        ChatForm.setWindowTitle(_translate("ChatForm", "Form"))


import ui.pictures_rc
