# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DownloadWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_downloadWindow(object):
    def setupUi(self, downloadWindow):
        downloadWindow.setObjectName("downloadWindow")
        downloadWindow.resize(712, 569)
        downloadWindow.setFixedSize(downloadWindow.width(),downloadWindow.height())
        self.flashButton = QtWidgets.QPushButton(downloadWindow)
        self.flashButton.setGeometry(QtCore.QRect(210, 490, 121, 41))
        self.flashButton.setObjectName("flashButton")
        self.comfirmButton = QtWidgets.QPushButton(downloadWindow)
        self.comfirmButton.setGeometry(QtCore.QRect(400, 490, 121, 41))
        self.comfirmButton.setObjectName("comfirmButton")
        self.fileNameEdit = QtWidgets.QLineEdit(downloadWindow)
        self.fileNameEdit.setGeometry(QtCore.QRect(160, 370, 391, 41))
        self.fileNameEdit.setObjectName("fileNameEdit")
        self.filePlaceEdit = QtWidgets.QLineEdit(downloadWindow)
        self.filePlaceEdit.setGeometry(QtCore.QRect(160, 430, 391, 41))
        self.filePlaceEdit.setObjectName("filePlaceEdit")
        self.listWidget = QtWidgets.QListWidget(downloadWindow)
        self.listWidget.setGeometry(QtCore.QRect(160, 20, 391, 341))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(downloadWindow)
        QtCore.QMetaObject.connectSlotsByName(downloadWindow)

    def retranslateUi(self, downloadWindow):
        _translate = QtCore.QCoreApplication.translate
        downloadWindow.setWindowTitle(_translate("downloadWindow", "Form"))
        self.flashButton.setText(_translate("downloadWindow", "刷新列表"))
        self.comfirmButton.setText(_translate("downloadWindow", "确定下载"))
