# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loadWindow(object):
    def setupUi(self, loadWindow):
        loadWindow.setObjectName("loadWindow")
        loadWindow.resize(505, 358)
        loadWindow.setFixedSize(loadWindow.width(), loadWindow.height())
        self.uploadPushButton = QtWidgets.QPushButton(loadWindow)
        self.uploadPushButton.setGeometry(QtCore.QRect(180, 130, 141, 41))
        self.uploadPushButton.setObjectName("uploadPushButton")
        self.downloadPushButton = QtWidgets.QPushButton(loadWindow)
        self.downloadPushButton.setGeometry(QtCore.QRect(180, 200, 141, 41))
        self.downloadPushButton.setObjectName("downloadPushButton")

        self.retranslateUi(loadWindow)
        QtCore.QMetaObject.connectSlotsByName(loadWindow)

    def retranslateUi(self, loadWindow):
        _translate = QtCore.QCoreApplication.translate
        loadWindow.setWindowTitle(_translate("loadWindow", "Form"))
        self.uploadPushButton.setText(_translate("loadWindow", "上传"))
        self.downloadPushButton.setText(_translate("loadWindow", "下载"))
