# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_login.ui'
#
# Created by: PyQt5 ui code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QWidget, QLineEdit


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(587, 405)
        loginWindow.setFixedSize(loginWindow.width(), loginWindow.height())
        self.loginButton = QtWidgets.QPushButton(loginWindow)
        self.loginButton.setGeometry(QtCore.QRect(170, 320, 271, 41))
        self.loginButton.setObjectName("loginButton")
        self.registerButton = QtWidgets.QPushButton(loginWindow)
        self.registerButton.setGeometry(QtCore.QRect(10, 360, 101, 31))
        self.registerButton.setObjectName("RegisterButton")
        self.userLineEdit = QtWidgets.QLineEdit(loginWindow)
        self.userLineEdit.setGeometry(QtCore.QRect(190, 180, 231, 31))
        self.userLineEdit.setObjectName("userLineEdit")
        self.pwdLineEdit = QtWidgets.QLineEdit(loginWindow)
        self.pwdLineEdit.setGeometry(QtCore.QRect(190, 240, 231, 31))
        self.pwdLineEdit.setObjectName("pwdLineEdit")
        self.pwdLineEdit.setEchoMode(QLineEdit.Password)
        self.autoCheck = QtWidgets.QCheckBox(loginWindow)
        self.autoCheck.setGeometry(QtCore.QRect(170, 290, 92, 20))
        self.autoCheck.setObjectName("AutoCheck")
        self.remPwdCheck = QtWidgets.QCheckBox(loginWindow)
        self.remPwdCheck.setGeometry(QtCore.QRect(370, 290, 92, 20))
        self.remPwdCheck.setObjectName("remPwdCheck")
        self.headimage = QtWidgets.QPushButton(loginWindow)
        self.headimage.setGeometry(QtCore.QRect(250, 60, 111, 101))
        self.headimage.setObjectName("headimage")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Form"))
        self.loginButton.setText(_translate("loginWindow", "安全登录"))
        self.registerButton.setText(_translate("loginWindow", "注册账号"))
        self.autoCheck.setText(_translate("loginWindow", "自动登录"))
        self.remPwdCheck.setText(_translate("loginWindow", "记住密码"))
