# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.setWindowModality(QtCore.Qt.NonModal)
        MainForm.resize(348, 808)
        self.pushButton = QtWidgets.QPushButton(MainForm)
        self.pushButton.setGeometry(QtCore.QRect(30, 740, 50, 50))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MainForm)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 740, 50, 50))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(MainForm)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 740, 50, 50))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(MainForm)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 740, 50, 50))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.listWidget = QtWidgets.QListWidget(MainForm)
        self.listWidget.setGeometry(QtCore.QRect(5, 91, 341, 641))
        self.listWidget.setObjectName("listWidget")
        self.headPortait = QtWidgets.QLabel(MainForm)
        self.headPortait.setGeometry(QtCore.QRect(20, 10, 72, 72))
        self.headPortait.setText("")
        self.headPortait.setObjectName("headPortait")
        self.pushButton_5 = QtWidgets.QPushButton(MainForm)
        self.pushButton_5.setGeometry(QtCore.QRect(270, 740, 50, 50))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(MainForm)
        self.pushButton_6.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.nicknamelable = QtWidgets.QLabel(MainForm)
        self.nicknamelable.setGeometry(QtCore.QRect(100, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nicknamelable.setFont(font)
        self.nicknamelable.setText("")
        self.nicknamelable.setObjectName("nicknamelable")
        self.IDlabel = QtWidgets.QLabel(MainForm)
        self.IDlabel.setGeometry(QtCore.QRect(100, 50, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.IDlabel.setFont(font)
        self.IDlabel.setText("")
        self.IDlabel.setObjectName("IDlabel")

        self.retranslateUi(MainForm)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "主窗口"))
